import type { Metadata } from "next";
import "./globals.css";
import { Roboto as Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";
import Header, { HeaderButton } from "@/components/header/Header";
import _QueryClientProvider from "../_QueryClientProvider";

const inter = Inter({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Header
          buttons={[
            <HeaderButton key="home" text="Home" href="/" />,
          ]} />
        <div className="flex min-h-screen">
          <Sidebar />
          <_QueryClientProvider>
            <main className="flex-1 overflow-auto p-6 relative">
              {children}
            </main>
          </_QueryClientProvider>
        </div>
      </body>
    </html>
  );
}
